# Generated by Django 4.1.5 on 2023-01-18 18:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 18, 23, 55, 454969, tzinfo=datetime.timezone.utc), verbose_name='Когда доставить'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/bouquets', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/shops', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Изображение'),
        ),
    ]
