# Generated by Django 4.1.5 on 2023-01-19 17:47

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_order', '0002_order_delivery_at_alter_bouquet_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 17, 47, 38, 246009, tzinfo=datetime.timezone.utc), verbose_name='Когда доставить'),
        ),
    ]
