# Generated by Django 4.1.5 on 2023-01-20 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_order', '0005_order_comment_alter_order_delivery_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bouquets',
            field=models.ManyToManyField(related_name='orders', to='flower_order.bouquet', verbose_name='Букеты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 18, 40, 10, 194839, tzinfo=datetime.timezone.utc), verbose_name='Когда доставить'),
        ),
    ]
